# Generated by Django 4.2.6 on 2023-10-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя аэропорта')),
                ('created_at', models.DateField(verbose_name='Основан в')),
                ('planes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plane.plane', verbose_name='Самолеты аэропорта')),
            ],
        ),
    ]
