# Generated by Django 4.2.6 on 2023-10-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plane', '0001_initial'),
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=256, verbose_name='Откуда')),
                ('to_place', models.CharField(max_length=256, verbose_name='Куда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена билета')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.airline', verbose_name='Аэропорт рейса')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plane.plane', verbose_name='Самолет рейса')),
            ],
        ),
    ]
